# Generated by Django 3.2.5 on 2021-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.AddField(
            model_name='tweet',
            name='domain_name',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
