# Generated by Django 3.2.5 on 2021-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0003_auto_20210721_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
