# Generated by Django 3.2.5 on 2021-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0004_domain_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='screen_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
